#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$HOME/.config/opencode/agents" "$HOME/.config/opencode/command" "$HOME/.local/bin"
chmod +x "$ROOT/bin/hx"
ln -sf "$ROOT/bin/hx" "$HOME/.local/bin/hx"
ln -sf "$ROOT/opencode/agents/hunt.md" "$HOME/.config/opencode/agents/hunt.md"
ln -sf "$ROOT/opencode/agents/hunt-auto.md" "$HOME/.config/opencode/agents/hunt-auto.md"
ln -sf "$ROOT/opencode/commands/brief.md" "$HOME/.config/opencode/command/brief.md"
ln -sf "$ROOT/opencode/commands/next.md" "$HOME/.config/opencode/command/next.md"
ln -sf "$ROOT/opencode/commands/debrief.md" "$HOME/.config/opencode/command/debrief.md"
echo "symlinks ok"
echo "adicione ao array plugin do ~/.config/opencode/opencode.jsonc:"
echo "\"file://$ROOT/opencode/plugin/hunt.ts\""
echo "reinicie o opencode depois de editar o config (nao ha hot reload)"
